%YAML:1.0
# dataset directory
dataset_dir: /home/luo/下载/KITTI/dataset/sequences/00

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50